<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CSS-D-196" name="com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport" tests="5" failures="2" timestamp="27 Apr 2020 13:52:44 GMT" time="1.332" errors="0">
  <testcase name="ValidateBrokerDBReport" time="0.336" classname="com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport"/>
  <testcase name="ValidateBrokerDBReport" time="0.195" classname="com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport"/>
  <testcase name="ValidateBrokerDBReport" time="0.353" classname="com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport"/>
  <testcase name="ValidateBrokerDBReport" time="0.209" classname="com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct BROK5_GST Is displayed expected [0.00450] but found [0.0045]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct BROK5_GST Is displayed expected [0.00450] but found [0.0045]
at org.testng.Assert.fail(Assert.java:96)
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:188)
at com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport.ValidateBrokerDBReport(ValidateDBBrokerReport.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidateBrokerDBReport -->
  <testcase name="ValidateBrokerDBReport" time="0.239" classname="com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Correct BROK5_GST Is displayed expected [0.00450] but found [0.0045]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Correct BROK5_GST Is displayed expected [0.00450] but found [0.0045]
at org.testng.Assert.fail(Assert.java:96)
at com.concerto.common.utilities.Asserts.AssertAll(Asserts.java:188)
at com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport.ValidateBrokerDBReport(ValidateDBBrokerReport.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ValidateBrokerDBReport -->
</testsuite> <!-- com.concerto.vegaah.test.scenarios.VegaahReports.ValidateDBBrokerReport -->
